version: "3.8"

services:
  app:
    image: mehradharmi1/two-tier-backend:latest
    container_name: message-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql-data:

networks:
  my-network:
